# Generated by Django 6.0.3 on 2026-05-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('topic', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('golang', 'Go'), ('rust', 'Rust'), ('typescript', 'TypeScript'), ('django', 'Django'), ('fastapi', 'FastAPI'), ('flask', 'Flask'), ('nodejs', 'Node.js'), ('react', 'React'), ('nextjs', 'Next.js'), ('vue', 'Vue.js'), ('angular', 'Angular'), ('sql', 'SQL'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('elasticsearch', 'Elasticsearch'), ('dsa', 'Data Structures & Algorithms'), ('os', 'Operating Systems'), ('networking', 'Computer Networks'), ('dbms', 'Database Management'), ('system_design', 'System Design'), ('hld', 'High Level Design'), ('lld', 'Low Level Design'), ('microservices', 'Microservices'), ('api_design', 'API Design'), ('devops', 'DevOps'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('gcp', 'Google Cloud'), ('azure', 'Azure'), ('ci_cd', 'CI/CD'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('nlp', 'Natural Language Processing'), ('computer_vision', 'Computer Vision'), ('mlops', 'MLOps'), ('llm', 'Large Language Models'), ('android', 'Android'), ('ios', 'iOS'), ('react_native', 'React Native'), ('flutter', 'Flutter'), ('cybersecurity', 'Cybersecurity'), ('web_security', 'Web Security'), ('cryptography', 'Cryptography'), ('behavioural', 'Behavioural'), ('leadership', 'Leadership'), ('problem_solving', 'Problem Solving')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=10)),
                ('question_type', models.CharField(choices=[('theoretical', 'Theoretical'), ('coding', 'Coding'), ('system_design', 'System Design'), ('behavioural', 'Behavioural'), ('debugging', 'Debugging'), ('case_study', 'Case Study')], default='theoretical', max_length=20)),
                ('expected_answer', models.TextField()),
                ('follow_up_questions', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('times_asked', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
