# Generated by Django 6.0.3 on 2026-05-09 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('recommendation', models.CharField(choices=[('strong_hire', 'Strong Hire'), ('hire', 'Hire'), ('maybe', 'Maybe'), ('no_hire', 'No Hire'), ('strong_no_hire', 'Strong No Hire')], max_length=20)),
                ('summary', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('topic_scores', models.JSONField(default=dict)),
                ('detailed_feedback', models.TextField()),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interviews.interview')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
