# Generated by Django 6.0.3 on 2026-05-09 20:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('behavioural', 'Behavioural'), ('system_design', 'System Design'), ('coding', 'Coding Round'), ('hr', 'HR Round'), ('mixed', 'Mixed')], default='technical', max_length=20)),
                ('topics', models.JSONField(default=list)),
                ('difficulty_level', models.CharField(default='medium', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('overall_score', models.FloatField(default=0.0)),
                ('interviewer_notes', models.TextField(blank=True, null=True)),
                ('is_recorded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('candidate_answer', models.TextField(blank=True, null=True)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('is_skipped', models.BooleanField(default=False)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interview_questions',
                'ordering': ['order'],
            },
        ),
    ]
