# Generated by Django 6.0.3 on 2026-05-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=10.0)),
                ('feedback', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('keywords_matched', models.JSONField(default=list)),
                ('keywords_missed', models.JSONField(default=list)),
                ('confidence_level', models.CharField(default='medium', max_length=20)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(default='gpt-4', max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ai_evaluations',
            },
        ),
    ]
