# Generated by Django 6.0.3 on 2026-05-09 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievaluation',
            name='interview_question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='interviews.interviewquestion'),
        ),
    ]
