# Generated by Django 6.0.3 on 2026-05-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('interview_scheduled', 'Interview Scheduled'), ('interview_started', 'Interview Started'), ('interview_completed', 'Interview Completed'), ('report_ready', 'Report Ready'), ('score_updated', 'Score Updated'), ('invitation', 'Invitation'), ('reminder', 'Reminder')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
